Remove missing dock-sound.patch from specfile
The patch was found to cause regressions and it was removed on commit
75a4ea729bbd ("Turns out the fix to enable dock sound breaks things")
but it remains in the specfile, so building the package fails:

ERROR: Patch  dock-sound.patch  listed in specfile but is missing
error: Bad exit status from /var/tmp/rpm-tmp.MK3pFg (%prep)
    Bad exit status from /var/tmp/rpm-tmp.MK3pFg (%prep)